
**[Problem 2] Calculation by NumPy function**

Now, let's use NumPy to calculate the matrix product.

```python

```

This will output the same matrix as the one calculated manually.

**[Problem 3] Implementation of calculation of a certain element**

Now, let's write code to calculate a specific element without using np.matmul(), np.dot(), or @ operators.

```python
def calculate_element(a, b, i, j):
    element = 0
    for k in range(len(a[0])):
        element += a[i, k] * b[k, j]
    return element

# Example usage:
element_00 = calculate_element(a_ndarray, b_ndarray, 0, 0)
print(element_00)
```

**[Problem 4] Creating a function that performs matrix multiplication**

Now, let's extend the code to create a function that performs matrix multiplication.

```python
def matrix_multiply(a, b):
    c = np.zeros((len(a), len(b[0])))
    for i in range(len(a)):
        for j in range(len(b[0])):
            c[i, j] = calculate_element(a, b, i, j)
    return c

# Example usage:
result_scratch = matrix_multiply(a_ndarray, b_ndarray)
print(result_scratch)
```

This function should produce the same result as the NumPy calculation.

**[Problem 5] Judge the input whose calculation is not defined**

Now, let's add a check to see if the multiplication is defined before performing the multiplication.

```python
def matrix_multiply_safe(a, b):
    if len(a[0]) != len(b):
        print("Matrix multiplication is not defined for the given matrices.")
        return None
    else:
        return matrix_multiply(a, b)

# Example usage:
result_safe = matrix_multiply_safe(d_ndarray, e_ndarray)
if result_safe is not None:
    print(result_safe)
```

**[Problem 6] Transposition**

Now, let's transpose matrix D and calculate the matrix product.

```python
d_transposed = np.transpose(d_ndarray)
result_transposed = np.matmul(d_transposed, e_ndarray)

# Alternatively, you can use d_transposed @ e_ndarray
# result_transposed = d_transposed @ e_ndarray

print(result_transposed)
```

This should give you the matrix product using the transposed matrix.

[Problem 2] Calculation by NumPy function

In [1]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

result = np.matmul(a_ndarray, b_ndarray)
print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


[Problem 3] Implementation of calculation of a certain element

Now, let's write code to calculate a specific element without using np.matmul(), np.dot(), or @ operators.

In [2]:
def calculate_element(a, b, i, j):
    element = 0
    for k in range(len(a[0])):
        element += a[i, k] * b[k, j]
    return element

element_00 = calculate_element(a_ndarray, b_ndarray, 0, 0)
print(element_00)


6


[Problem 4] Creating a function that performs matrix multiplication

Now, let's extend the code to create a function that performs matrix multiplication

In [3]:
def matrix_multiply(a, b):
    c = np.zeros((len(a), len(b[0])))
    for i in range(len(a)):
        for j in range(len(b[0])):
            c[i, j] = calculate_element(a, b, i, j)
    return c

result_scratch = matrix_multiply(a_ndarray, b_ndarray)
print(result_scratch)


[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


[Problem 5] Judge the input whose calculation is not defined



In [6]:
import numpy as np

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def matrix_multiply_safe(a, b):
    if len(a[0]) != len(b):
        print("Matrix multiplication is not defined for the given matrices.")
        return None
    else:
        return matrix_multiply(a, b)

result_safe = matrix_multiply_safe(d_ndarray, e_ndarray)
if result_safe is not None:
    print(result_safe)


Matrix multiplication is not defined for the given matrices.


[Problem 6] Transposition



In [7]:
d_transposed = np.transpose(d_ndarray)
result_transposed = np.matmul(d_transposed, e_ndarray)

# Alternatively, you can use d_transposed @ e_ndarray
# result_transposed = d_transposed @ e_ndarray

print(result_transposed)



[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
